Repository Step3-kakao-tech-campus/Team5_BE, pull requests merged in 2023-11, with the labels that each got.

#134 Review, Chat 테스트 코드 작성
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/DateFormat.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/ReviewStatus.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: Done, test, review, chat

#136 리뷰 기능 수정 및 페이지네이션 구현
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: Done, test, refactor, review

#139 찜하기 기능 구현
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/Favorite.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/Payment.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/_core/DummyEntity.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java
Labels: enhancement, Done, favorites

#133 코드 리팩토링 진행
  .github/workflows/spring-boot-ci.yml
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/SunsuWeddingApplication.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/EnvConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/CustomException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/GlobalExceptionHandler.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/BadRequestException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ForbiddenException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/NotFoundException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ServerException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/TokenException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/UnauthorizedException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JWTProvider.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtExceptionFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/ApiUtils.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/FilterResponseUtils.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/TokenResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioSpecification.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/ErrorStatus.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenService.java
  sunsu-wedding/src/main/resources/env/env.yaml
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/SunsuWeddingApplicationTests.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java
Labels: Done, refactor

#144 견적서, 리뷰 모아보기 기능 수정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/Quotation.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
Labels: Done, refactor, quotation, review

#145 포트폴리오, 전체 코드 리팩토링
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/CustomUserDetails.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/PriceCalculator.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItemJDBCRepositoryImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItemJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItemService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/price/PriceItemJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenService.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/_core/DummyEntity.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java
Labels: Done, portfolio, refactor

#148 회원가입 이메일 인증 로직 구현
  .github/workflows/spring-boot-ci.yml
  sunsu-wedding/build.gradle
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/EmailConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailCode.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailCodeController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailCodeJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailService.java
  sunsu-wedding/src/main/resources/env/env.yaml
Labels: enhancement, Done, user

#149 이미지, 가격 JPARepository, PriceCalculator 테스트코드 작성
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/_core/DummyEntity.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/image/ImageItemJPARepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/price/PriceItemJPARepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/util/PriceCalculatorTest.java
Labels: Done, test, portfolio

#154 포트폴리오 테스트코드, 리뷰 별점
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/Review.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/mail/MailCodeController.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java
Labels: Done, test, portfolio

#159 포트폴리오 테스트 코드 에러 해결 및 주석 해제
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
Labels: Done, test

#162 Controller, Service 메서드명 통일
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: Done, refactor

#163 리뷰 이미지 아이템 구현
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/PortfolioImageItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/PortfolioImageItemJDBCRepositoryImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItemJDBCRepositoryImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItemJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItemService.java
  sunsu-wedding/src/main/resources/db/teardown.sql
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/image/PortfolioImageItemJPARepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRepositoryTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: Done, review

#166 엔드포인트 변경 및 찜하기 별점 추가
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: enhancement, Done

#167 리뷰 , 채팅 관련 DTO 수정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
Labels: refactor

#171 CORS 설정, 토큰 검증 API 추가, DTO 제약조건 추가, 리팩토링
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/constants/Constants.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/BadRequestException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ForbiddenException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/NotFoundException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ServerException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/UnauthorizedException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailCodeRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenService.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenServiceImpl.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java
Labels: bug, refactor

#173 사용자 권한 인증 및 RequestBody에 제약 조건 추가
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/TokenException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtExceptionFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailCodeRestController.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
Labels: enhancement, Done, refactor

#175 리드미 파일 업데이트
  README.md
Labels: documentation

#178 토큰 에러 검출 api 추가, 에러 메시지 내용 수정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/GlobalExceptionHandler.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioSpecification.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailServiceImpl.java
  sunsu-wedding/src/main/resources/db/teardown.sql
Labels: bug, refactor

#181 CORS 설정 및 Validation 에러 메시지 수정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
Labels: refactor

#182 플래너별 리뷰 조회 권한 설정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
Labels: bug

#189 탈퇴한 유저 견적서 추가 버그 수정
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationServiceImpl.java
Labels: bug, quotation

#190 README 파일 수정
  README.md
Labels: documentation

#191 토큰 시간 변경, 데이터베이스 조회 메서드 분리
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JWTProvider.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/chat/ChatServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationServiceImpl.java
Labels: refactor

#192 테이블 인덱스 추가
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtExceptionFilter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/Favorite.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/Payment.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/PortfolioImageItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/price/PriceItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/Quotation.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewJPARepository.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItem.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/base_user/User.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailCode.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/Token.java
Labels: enhancement, refactor

#194 Request Body에 길이 제약 조건 추가
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/PriceCalculator.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioServiceImpl.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/Quotation.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/Review.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
  sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/base_user/User.java
  sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
Labels: bug, enhancement
